name: Version checker

on:
  schedule:
    - cron: '*/5 * * * *'     

  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout Repo-A
        uses: actions/checkout@v4
        with:
          repository: Utkarshnegi2k5/Repo-A
          token: ${{ secrets.VERSION_TOKEN }}
          path: Repo-A

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Run version checker
        env:
          VERSION_TOKEN: ${{secrets.VERSION_TOKEN}}
        

        run: node version-checker.js